spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: pcodes
    password: pcodes
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8050